site_name: Code Over Time [ALPHA]
site_url: https://codeovertime.com/
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    - scheme: default
      primary: black
      toggle:
        primary: black
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Light mode
nav: 
  - Welcome: index.md
  - Curriculum: curriculum.md
  - Reading Material:
    - Systems:
        Introduction: reading_material/systems/index.md
        Inputs & Outputs: reading_material/systems/io.md
    - Hardware:
        Introduction: reading_material/hardware/index.md
        Mouse & Keyboard: reading_material/hardware/keyboards_and_mice.md
    - Software:
        Introduction: reading_material/software/index.md
    - Coding:
        Introduction: reading_material/coding/index.md
        Where to start: reading_material/coding/languages.md
  - Your Internship:
    - Overview: internship/internship.md
    - Getting Set Up:
      - Introduction: internship/setup/index.md
      - Dev Environment:
        - Overview: internship/setup/environment_setup/intro.md
        - Linux: internship/setup/environment_setup/linux.md
        - Windows: internship/setup/environment_setup/windows.md
        - OSX: internship/setup/environment_setup/osx.md
        - Testing your setup: internship/setup/environment_setup/testing_your_setup.md
      - Project Setup:
        - Varcade Games: internship/setup/varcade_games/intro.md
        - Get the code: internship/setup/varcade_games/get_the_code.md
        - Running Varcade Games: internship/setup/varcade_games/running_vcg.md
        - Adding a game: internship/setup/varcade_games/adding_a_game.md
      - Next Steps: internship/setup/next_steps.md
    - Onboarding:
      - Introduction: internship/onboarding/index.md
      - Varcade Games:
        - Introduction: internship/onboarding/varcade_games/intro_client.md
        - System Architecture: internship/onboarding/varcade_games/system_architecture.md
        - Reverse Engineering: internship/onboarding/varcade_games/reverse_engineering.md
        - Making Changes: internship/onboarding/varcade_games/making_changes.md
        - Tests and Linters: internship/onboarding/varcade_games/tests_and_linters.md
      - Plugging in games:
        - Introduction: internship/onboarding/varcade_games/intro_server.md
        - The Admin panel: internship/onboarding/varcade_games/admin.md
        - Embedding games: internship/onboarding/varcade_games/embedding_games.md
        - The Matchmaker: internship/onboarding/varcade_games/matchmaker.md
      - The Game Client:
        - Introduction: internship/onboarding/rps_game/intro.md
        - Working with Rock Paper Scissors Apocalypse: internship/onboarding/rps_game/working_with_the_game.md
        - Key Concepts: internship/onboarding/rps_game/key_concepts.md
        - Single player: internship/onboarding/rps_game/single_player_mode.md
        - The Game Engine: internship/onboarding/rps_game/the_game_engine.md
        - Game Design: internship/onboarding/rps_game/game_design.md
      - The Game Server:
        - Introduction: internship/onboarding/rps_game_server/intro.md
        - Playing with Others: internship/onboarding/rps_game_server/playing_with_others.md
        - Key Concepts: internship/onboarding/rps_game_server/key_concepts.md
        - System Design: internship/onboarding/rps_game_server/system_design.md
        - The Game Engine: internship/onboarding/rps_game_server/the_game_engine.md
      - Backend Services:
        - Introduction: internship/onboarding/backend/intro.md
        - The Matchmaker: internship/onboarding/backend/matchmaker.md
        - Working with the Matchmaker: internship/onboarding/backend/working_with_matchmaker.md
        - The Workers: internship/onboarding/backend/workers.md
        - The Stats Tracker: internship/onboarding/backend/stats_tracker.md
      - Instrumentation:
        - Introduction: internship/onboarding/instrumentation/intro.md
        - Setting up Grafana: internship/onboarding/instrumentation/grafana.md
        - Running a load test: internship/onboarding/instrumentation/load_test.md
      - Next Steps: internship/onboarding/closing_words.md
    - Hands-on Tasks:
      - How It Works: internship/tasks/overview.md
      - Junior:
          - Keyboard Shortcuts: internship/tasks/junior/001_keyboard_login.md
          - Skip, Skip Skip: internship/tasks/junior/002_skip_cutscene.md
          - Build Tools: internship/tasks/junior/003_build_tools.md
          - Error Handling: internship/tasks/junior/004_error_handling.md
          - Stats UI Design: internship/tasks/junior/005_stats_ui_design.md
          - Error Handling 2: internship/tasks/junior/007_error_handling_2.md
          - Test Coverage: internship/tasks/junior/008_test_coverage.md
      - Mid:
          - Settings Menu: internship/tasks/mid/001_game_settings.md
          - User Cleanup: internship/tasks/mid/002_user_cleanup.md
      - Senior:
          - Per Round Stats: internship/tasks/senior/000_per_round_stats.md
          - De-duplication: internship/tasks/senior/001_deduplication.md
      - Principle:
          - Async Game Server: internship/tasks/principle/001_async_node.md
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true